model_params:
  image_size: 128
  num_hiddens: 128
  num_downsampling_layers: 2
  num_upsampling_layers: 2
  num_residual_layers: 4
  num_residual_hiddens: 32
  num_embeddings: 4096
  embedding_dim: 256
  commitment_cost: 0.25
  decay: 0.99

train_params:
  task_name: 'vqvae_naruto_v2'
  batch_size: 64
  epochs: 1000
  lr: 0.0001
  ckpt_name: 'best_vqvae_naruto_v2.pth'
  seed: 111
  output_train_dir: 'output'
  dataset: 'naruto'

lstm_params:
  embedding_dim: 256
  hidden_size: 512
  epochs: 100