model_params:
  image_size: 128
  num_hiddens: 128
  num_downsampling_layers: 2
  num_upsampling_layers: 2
  num_residual_layers: 4
  num_residual_hiddens: 32
  num_embeddings: 4096
  embedding_dim: 256
  commitment_cost: 0.25
  decay: 0.99

train_params:
  task_name: 'vqvae_naruto_v2'
  batch_size: 16
  epochs: 1000
  lr: 0.0001
  ckpt_name: 'best_vqvae_naruto_v2.pth'
  seed: 111
  output_train_dir: 'output'
  dataset: 'naruto'

lstm_params:
  embedding_dim: 256
  hidden_size: 512
  epochs: 100

transformer_params:
  n_layer: 8
  n_head: 8
  n_embd: 512
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  lr: 0.0003
  epochs: 200
  temperature: 0.8

cftn_params:
  n_layer: 12
  n_head: 8
  n_embd: 768
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  lr: 0.0001
  epochs: 500
  temperature: 1.0
  text_block_size: 128
  steps: 12

cftn_v2_params:
  n_layer: 12
  n_head: 4
  n_embd: 256
  bridge_ratio: 0.33
  epochs_bidirectional: 500
  epochs_gen_only: 200
  lr_text: 0.0002
  lr_gate: 0.05
  text_block_size: 256
  eval_every: 10
  target_img_loss: 0.1
