model_params:
  in_channels: 3
  convbn_blocks: 4
  conv_kernel_size: [4, 4, 4, 4]
  conv_kernel_strides: [2, 2, 2, 2]
  convbn_channels: [3, 64, 128, 256, 512]
  conv_activation_fn: 'leaky'
  transpose_bn_blocks: 4
  transposebn_channels: [512, 256, 128, 64, 3]
  transpose_kernel_size: [4, 4, 4, 4]
  transpose_kernel_strides: [2, 2, 2, 2]
  transpose_padding: [1, 1, 1, 1]
  transpose_activation_fn: 'leaky'
  latent_dim: 256
  codebook_size : 1024
  decay: 0.99
  epsilon: 1e-5

train_params:
  task_name: 'vqvae_naruto'
  batch_size: 32
  epochs: 200
  lr: 0.0002
  crit: 'l1'
  reconstruction_loss_weight : 1
  codebook_loss_weight : 1
  commitment_loss_weight : 1.0
  ckpt_name: 'best_vqvae_naruto.pth'
  seed: 111
  save_training_image: True
  output_train_dir: 'output'
  dataset: 'naruto'

lstm_params:
  embedding_dim: 256
  hidden_size: 512
  epochs: 50
